import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import {webcrypto} from 'node:crypto';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const assert=(ok,msg)=>{if(!ok)throw new Error(msg);};
const pages=['index.html','project2.html','experiment.html','share.html','experience.html','aggregate.html','setup.html','admin.html'];
for(const file of pages){const html=read(file);for(const m of html.matchAll(/<script\s+src="([^"]+)"/g))assert(fs.existsSync(path.join(root,m[1])),`${file}: missing ${m[1]}`);for(const m of html.matchAll(/(?:src|href)="([^"#?]+)"/g)){const ref=m[1];if(ref&&!/^(?:[a-z]+:|\/\/)/i.test(ref))assert(fs.existsSync(path.join(root,ref)),`${file}: missing ${ref}`);}assert(!html.includes('p2-06'),`${file}: must not contain P2-06 runtime copy`);}
assert(/P2-07/.test(read('index.html'))&&/09:00/.test(read('experiment.html'))&&/20:00/.test(read('experiment.html')),'pages must describe P2-07 and both times');
assert(/experience\.html/.test(read('share.html')+read('assets/share.js')),'registration must lead to experience page');
assert(/点击率|CTR/.test(read('aggregate.html'))&&/CSV/.test(read('aggregate.html')),'aggregate must expose CTR and CSV');
assert(!/simulateDataUpdate|seedDemo|randInt\(/.test(read('experiment.html')+read('aggregate.html')),'platform must not fabricate samples');
const ids=(html)=>new Set([...html.matchAll(/\bid="([^"]+)"/g)].map(x=>x[1]));
for(const [html,js] of [['share.html','assets/share.js'],['experience.html','assets/engagement.js'],['experiment.html','assets/workbench.js'],['aggregate.html','assets/aggregate.js'],['setup.html','assets/setup.js']]){const set=ids(read(html));for(const m of read(js).matchAll(/getElementById\(['"]([^'"]+)['"]\)/g))assert(set.has(m[1]),`${js}: missing #${m[1]} in ${html}`);}
const store=new Map(),localStorage={getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k)};
const context={window:{AB_CONFIG:{studyKey:'p2-07-campus-push-time-v1',apiBase:'',allowPreviewOverride:true}},localStorage,crypto:webcrypto,location:{search:''},URLSearchParams,fetch:globalThis.fetch,console,Date,Math,Number,String,JSON,Array,Object,Promise,setTimeout,clearTimeout};vm.createContext(context);vm.runInContext(read('assets/shared.js'),context);const P=context.window.P2;
P.setProfile({studentId:'2024010101',name:'测试同学',className:'市场营销2024-1班'});const s=P.createSession(true);assert(s.studyKey==='p2-07-campus-push-time-v1'&&s.studentId==='2024010101','session must use independent key and profile');const first=P.createSession(false);assert(first.participantId===s.participantId&&first.variant===s.variant,'formal participant must be stable');
await P.pushRecord(Object.assign({},s,{impressionAt:'2026-01-01T00:00:00Z',status:'started'}));await P.pushRecord(Object.assign({},s,{impressionAt:'2026-01-01T00:00:00Z',clickedAt:'2026-01-01T00:01:00Z',clickCount:1,status:'clicked'}));const rows=P.getLocalRecords();assert(rows.length===1&&rows[0].clickCount===1,'records must upsert by participant');
const summary=P.summarize([{variant:'A',status:'started',clickCount:0},{variant:'A',status:'clicked',clickCount:1},{variant:'B',status:'started',clickCount:0},{variant:'B',status:'clicked',clickCount:1}]);assert(summary.A.ctr===.5&&summary.B.ctr===.5&&summary.diff===0,'CTR summary arithmetic wrong');
const previewStore=new Map(),previewCtx={window:{AB_CONFIG:{studyKey:'p2-07-campus-push-time-v1',apiBase:'',allowPreviewOverride:true}},localStorage:{getItem:k=>previewStore.get(k)||null,setItem:(k,v)=>previewStore.set(k,String(v)),removeItem:k=>previewStore.delete(k)},crypto:webcrypto,location:{search:'?preview=B'},URLSearchParams,fetch:globalThis.fetch,console,Date,Math,Number,String,JSON,Array,Object,Promise,setTimeout,clearTimeout};vm.createContext(previewCtx);vm.runInContext(read('assets/shared.js'),previewCtx);const pv=previewCtx.window.P2.createSession(true);assert(pv.preview&&pv.variant==='B','preview variant wrong');await previewCtx.window.P2.pushRecord(Object.assign({},pv,{status:'completed',clickCount:1}));assert(!previewStore.has('p207_records_v1'),'preview must not write formal records');
const schema=read('worker/schema.sql'),worker=read('worker/src/index.js');assert(schema.includes('impression_at')&&schema.includes('click_count')&&schema.includes('participant_name'),'independent schema missing click/profile fields');assert(worker.includes('p2-07-campus-push-time-v1')&&worker.includes('MAX(participant_records.click_count'),'worker must be independent and monotonic');
const mod=await import(`data:text/javascript,${encodeURIComponent(worker)}`),calls=[];const fakeDB={prepare(sql){const q={bind(...args){calls.push({sql,args});return q;},async run(){return {success:true};},async all(){return {results:[{study_key:'p2-07-campus-push-time-v1',participant_id:'participant-12345678',student_id:'2024010101',participant_name:'测试同学',class_name:'市场营销2024-1班',variant:'B',status:'clicked',started_at:'2026-01-01T00:00:00Z',impression_at:'2026-01-01T00:00:00Z',clicked_at:'2026-01-01T00:01:00Z',completed_at:'',click_count:1,updated_at:'2026-01-01T00:01:00Z'}]};}};return q;}};const env={DB:fakeDB,ADMIN_TOKEN:'secret',ALLOWED_ORIGIN:'http://localhost:8000'};const post=await mod.default.fetch(new Request('https://p207.test/api/participant',{method:'POST',headers:{Origin:'http://localhost:8000','Content-Type':'application/json'},body:JSON.stringify({studyKey:'p2-07-campus-push-time-v1',record:{participantId:'participant-12345678',studentId:'2024010101',participantName:'测试同学',className:'市场营销2024-1班',variant:'B',status:'clicked',clickCount:1}})}),env);assert(post.status===200&&calls[0].args.includes(1),'worker must accept click record');const get=await mod.default.fetch(new Request('https://p207.test/api/results?studyKey=p2-07-campus-push-time-v1',{headers:{Authorization:'Bearer secret'}}),env),data=await get.json();assert(data.items[0].clickCount===1&&data.items[0].variant==='B','worker must return click record');
console.log('p2-07 smoke tests: PASS');
